version: "3.8"

services:
    flask-app:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - ./uploaded_inventory:/app/uploaded_inventory
        environment:
            - FLASK_ENV=development
